[build]
  command = 'npm run build'
  publish = 'dist'
  functions = './functions'

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888 
  publish = "dist"

[[redirects]]
from = '/api/*'
to = '/.netlify/functions/:splat'
status = 200